# .travis.yml
dist: xenial

language: php

php:
  - 7.2
  - 7.3
  - "7.4snapshot"

allow_failures:
  # Allow failures for unstable builds.
  - php: "7.4snapshot"

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - cp .env.example .env
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate --no-interaction -vvv
  - npm install

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - npm run production

after_success:
  - bash <(curl -s https://codecov.io/bash)
