version: '3'

services:
  web:
    environment:
    - PUBLIC_ROOT=html
    image: uofadarren/web
    networks:
    - my-network
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./:/var/www

  mysql:
    environment:
    - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    image: mariadb
    networks:
    - my-network
    ports:
    - 3306:3306
    volumes:
    - mysql-data:/var/lib/mysql

  redis:
    image: redis:4.0.9
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
    - 6379:6379
    networks:
    - my-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    ports:
    - 8082:8081
    environment:
      - REDIS_HOSTS=local:redis:6379
    networks:
    - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mysql-data:
