// npm install -g stylelint
// stylelint --fix **/*.scss
// if using in Atom, npm install stylelint
// https://stylelint.io/user-guide/rules/

module.exports = {
    'rules': {
        'at-rule-blacklist': [],
        'at-rule-empty-line-before': [
            'always',
            {
                'except': [
                    'blockless-after-blockless',
                    'inside-block',
                ],
                'ignore': 'after-comment',
                'ignoreAtRules': [
                    'import',
                    'media',
                ],
            },
        ],
        'at-rule-name-case': 'lower',
        'at-rule-name-newline-after': 'always-multi-line',
        'at-rule-name-space-after': 'always',
        'at-rule-no-unknown': [
            true,
            {
                'ignoreAtRules': [
                    'each',
                    'extend',
                    'for',
                    'if',
                    'import',
                    'include',
                    'mixin',
                ],
            },
        ],
        'at-rule-no-vendor-prefix': true,
        'at-rule-semicolon-newline-after': 'always',
        'at-rule-semicolon-space-before': 'never',
        'at-rule-whitelist': null,
        'block-closing-brace-empty-line-before': 'never',
        'block-closing-brace-newline-after': 'always-multi-line',
        'block-closing-brace-newline-before': 'always-multi-line',
        'block-closing-brace-space-after': 'always-single-line',
        'block-closing-brace-space-before': 'always-single-line',
        'block-no-empty': true,
        'block-opening-brace-newline-after': 'always-multi-line',
        'block-opening-brace-newline-before': 'never-single-line',
        'block-opening-brace-space-after': 'always-single-line',
        'block-opening-brace-space-before': 'always-multi-line',
        'color-hex-case': 'lower',
        'color-hex-length': 'short',
        'color-named': 'never',
        'color-no-invalid-hex': true,
        'comment-empty-line-before': 'always',
        'comment-no-empty': true,
        'comment-whitespace-inside': 'always',
        'comment-word-blacklist': null,
        'custom-media-pattern': null,
        'custom-property-empty-line-before': 'never',
        'custom-property-pattern': null,
        'declaration-bang-space-after': 'never',
        'declaration-bang-space-before': 'always',
        'declaration-block-no-duplicate-properties': true,
        'declaration-block-no-redundant-longhand-properties': true,
        'declaration-block-no-shorthand-property-overrides': true,
        'declaration-block-semicolon-newline-after': 'always-multi-line',
        'declaration-block-semicolon-newline-before': 'never-multi-line',
        'declaration-block-semicolon-space-after': 'always-single-line',
        'declaration-block-semicolon-space-before': 'never',
        'declaration-block-single-line-max-declarations': 1,
        'declaration-block-trailing-semicolon': 'always',
        'declaration-colon-space-after': 'always',
        'declaration-colon-space-before': 'never',
        'declaration-empty-line-before': 'never',
        'declaration-no-important': true,
        'declaration-property-unit-blacklist': null,
        'declaration-property-unit-whitelist': null,
        'declaration-property-value-blacklist': null,
        'declaration-property-value-whitelist': null,
        'font-family-name-quotes': 'always-where-recommended',
        'font-family-no-duplicate-names': true,
        'font-family-no-missing-generic-family-keyword': [
            true,
            {
                'severity': 'warning',
            },
        ],
        'font-weight-notation': [
            'named-where-possible',
            {
                'severity': 'warning',
            },
        ],
        'function-blacklist': [],
        'function-calc-no-unspaced-operator': true,
        'function-comma-newline-after': 'never-multi-line',
        'function-comma-newline-before': 'never-multi-line',
        'function-comma-space-after': 'always',
        'function-comma-space-before': 'never',
        'function-linear-gradient-no-nonstandard-direction': true,
        'function-max-empty-lines': 0,
        'function-name-case': 'lower',
        'function-parentheses-newline-inside': 'never-multi-line',
        'function-parentheses-space-inside': 'never',
        'function-url-no-scheme-relative': true,
        'function-url-quotes': 'always',
        'function-url-scheme-blacklist': null,
        'function-url-scheme-whitelist': null,
        'function-whitelist': null,
        'function-whitespace-after': 'always',
        'indentation': 4,
        'keyframe-declaration-no-important': true,
        'length-zero-no-unit': true,
        'max-empty-lines': 1,
        'max-line-length': [
            120,
            {
                'severity': 'warning',
            },
        ],
        'max-nesting-depth': 4,
        'media-feature-colon-space-after': 'always',
        'media-feature-colon-space-before': 'never',
        'media-feature-name-blacklist': null,
        'media-feature-name-case': 'lower',
        'media-feature-name-no-unknown': true,
        'media-feature-name-no-vendor-prefix': true,
        'media-feature-parentheses-space-inside': 'never',
        'media-feature-range-operator-space-after': 'always',
        'media-feature-range-operator-space-before': 'always',
        'media-query-list-comma-newline-after': 'always-multi-line',
        'media-query-list-comma-newline-before': 'never-multi-line',
        'media-query-list-comma-space-after': 'always',
        'media-query-list-comma-space-before': 'never',
        'no-descending-specificity': [
            true,
            {
                'severity': 'warning',
            },
        ],
        'no-duplicate-at-import-rules': true,
        'no-duplicate-selectors': true,
        'no-empty-source': [
            true,
            {
                'severity': 'warning',
            },
        ],
        'no-eol-whitespace': true,
        'no-extra-semicolons': true,
        'no-invalid-double-slash-comments': true,
        'no-missing-end-of-source-newline': true,
        'no-unknown-animations': [
            true,
            {
                'severity': 'warning',
            },
        ],
        'number-leading-zero': 'never',
        'number-max-precision': 4,
        'number-no-trailing-zeros': true,
        'property-blacklist': null,
        'property-case': 'lower',
        'property-no-unknown': true,
        'property-no-vendor-prefix': [
            true,
            {
                'severity': 'warning',
            },
        ],
        'property-whitelist': null,
        'rule-empty-line-before': [
            'always-multi-line',
            {
                'except': [
                    'after-single-line-comment',
                    'first-nested',
                    'inside-block',
                ],
                'ignore': 'inside-block',
            },
        ],
        'selector-attribute-brackets-space-inside': 'never',
        'selector-attribute-operator-blacklist': null,
        'selector-attribute-operator-space-after': 'never',
        'selector-attribute-operator-space-before': 'never',
        'selector-attribute-operator-whitelist': null,
        'selector-attribute-quotes': 'always',
        'selector-class-pattern': null,
        'selector-combinator-blacklist': null,
        'selector-combinator-whitelist': null,
        'selector-combinator-space-after': 'always',
        'selector-combinator-space-before': 'always',
        'selector-descendant-combinator-no-non-space': true,
        'selector-id-pattern': null,
        'selector-list-comma-newline-after': 'always-multi-line',
        'selector-list-comma-newline-before': 'never-multi-line',
        'selector-list-comma-space-after': 'always-single-line',
        'selector-list-comma-space-before': 'never',
        'selector-max-attribute': 2,
        'selector-max-class': 5,
        'selector-max-combinators': 4,
        'selector-max-compound-selectors': 5,
        'selector-max-empty-lines': 1,
        'selector-max-id': 0,
        'selector-max-specificity': null,
        'selector-max-type': 3,
        'selector-max-universal': 1,
        'selector-nested-pattern': null,
        'selector-no-qualifying-type': [
            true,
            {
                'ignore': [
                    'attribute',
                    'class', // includes ignoring pseudo-classes
                ],
            },
        ],
        'selector-no-vendor-prefix': [
            true,
            {
                'severity': 'warning',
            },
        ],
        'selector-pseudo-class-blacklist': null,
        'selector-pseudo-class-case': 'lower',
        'selector-pseudo-class-no-unknown': true,
        'selector-pseudo-class-parentheses-space-inside': 'never',
        'selector-pseudo-class-whitelist': null,
        'selector-pseudo-element-blacklist': null,
        'selector-pseudo-element-whitelist': null,
        'selector-pseudo-element-case': 'lower',
        'selector-pseudo-element-colon-notation': 'double',
        'selector-pseudo-element-no-unknown': true,
        'selector-type-case': 'lower',
        'selector-type-no-unknown': true,
        'shorthand-property-no-redundant-values': true,
        'string-no-newline': true,
        'string-quotes': 'single',
        'time-min-milliseconds': [
            20,
            {
                'severity': 'warning',
            },
        ],
        'unit-blacklist': null,
        'unit-case': 'lower',
        'unit-no-unknown': true,
        'unit-whitelist': null,
        'value-keyword-case': 'lower',
        'value-list-comma-newline-after': 'never-multi-line',
        'value-list-comma-newline-before': 'never-multi-line',
        'value-list-comma-space-after': 'always',
        'value-list-comma-space-before': 'never',
        'value-list-max-empty-lines': 0,
        'value-no-vendor-prefix': true,
    },
};
