# This is a basic workflow to help you get started with Actions

name: Auto Update Base Branches

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: automerge
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            var branches = await github.repos.listBranches({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
            });
            
            branches.data.forEach((branch) => {
              if (branch.name != 'master') {
                octokit.repos.merge({
                  owner: context.payload.repository.owner.login,
                  repo: context.payload.repository.name,
                  base: branch.name,
                  head: 'master',
                  commit_message: 'Automatically updating PR from base branch',
                });
              }
            });

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
