name: Continuous Integration

on: [push, pull_request]

jobs:
  run-tests:
    strategy:
      
      fail-fast: true
      
      matrix:
        os: [ubuntu-latest, windows-latest]
        php: [7.4]
        laravel: [6.*]
        stability: [prefer-lowest, prefer-stable]
        include:
          - laravel: 6.*
            testbench: 4.13

    runs-on: ubuntu-latest

    name: Laravel ${{ matrix.laravel }} - PHP ${{ matrix.php }} (${{ matrix.stability }}) - Running on ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Prepare Environment
        run: php artisan key:generate

      - name: Execute tests
        run: vendor/bin/phpunit


  auto-merge:
    runs-on: ubuntu-latest
    needs: [run-tests]

    if: github.event.pull_request.user.login == 'dependabot-preview[bot]'
    steps:
      - name: automerge
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.pullRequests.createReview({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            })
            
            github.pullRequests.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number
            })
